### ISSUE TITLE
Source unlicensed

### ISSUE THREAD

**Issue by ppfeister** [bernardoamc/text-placeholder#10]
The crates[.]io package uses MIT [or] Apache 2.0, while the source (this repository) is unlicensed.

Both the MIT and Apache licenses require that their text be included with the source. I request that either license (or both) be added to the source so that it can be [packaged on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2295138) and made available to more users.

If easier, I can PR this change. Just let me know.

Thanks!

**Comment by bernardoamc** [comment]
Interesting, thanks for letting me know @ppfeister! I will get to it today or tomorrow and update the issue.

I'm also guessing I will need to cut a new release for the crate?

**Comment by ppfeister** [comment]
Very quick reply. Thanks for that!

The crate would need to be updated as well, yes. I don't know if crate[.]io allows for it (I know PyPI doesn't), but since this is only a documentation change, I don't think a version bump is strictly necessary, personally. Just a rebuild so it's included.

Not that a bump in patch number is a bad thing either, just triggers notifications for some people

**Comment by bernardoamc** [comment]
> Very quick reply. Thanks for that!

I know how frustrating it can be to be blocked by something out of your control, so I'm glad I can help. :)

re:patch number bump, that is a good point. I will try to rebuild and will ping you after things are done.

**Comment by bernardoamc** [comment]
I've ended up bumping the minor version since I touched the `Cargo.toml` file in order to mention the license. It's a pretty conservative choice, but I hope no one is bothered by it. 🤞 

Hope this unblocks you!

**Comment by ppfeister** [comment]
Build succeeded and ticket updated
Not too long til it's approved for stable and the other dependents can take advantage

Much appreciated! I'll drop a message here once it's live just for some proper closure

**Comment by decathorpe** [comment]
Thanks for the quick turnaround here! I'm wondering if there was a specific reason to also re-license from the dual-MIT/Apache-2.0 license to just MIT?

**Comment by bernardoamc** [comment]
@decathorpe No particular reason besides my overall lack of knowledge on licenses. 😄 Anything I could do to help? What is encompassed within the Apache-2.0 license that attracts you?

**Comment by decathorpe** [comment]
Regarding making this crate available as a package in Fedora Linux, we don't have a preference between `MIT` or `Apache-2.0` or `MIT OR Apache-2.0`. I was just curious why seemingly unrelated tasks of "add license texts for project license" and "relicense project" happened at the same time.

**Comment by ppfeister** [comment]
We're good to go! Made it into stable this morning.

Thanks for clearing that blocker so readily

[![Packaging status](https://repology.org/badge/vertical-allrepos/rust:text-placeholder.svg)](https://repology.org/project/rust:text-placeholder/versions)

[__[repology]__](https://repology.org/project/rust:text-placeholder) [__[pkg src]__](https://src.fedoraproject.org/rpms/rust-text_placeholder)

**Comment by ppfeister** [comment]
Closing as solved now that the package is in stable.
